version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file_root:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: D:/myPython/myPython/logs/root.log
    maxBytes: 10485760     # 10MB
    backupCount: 5
    encoding: utf-8
  file_app:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: D:/myPython/myPython/logs/app.log
    maxBytes: 10485760     # 10MB
    backupCount: 5
    encoding: utf-8
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: D:/myPython/myPython/logs/error.log
    maxBytes: 5242880
    backupCount: 3
    encoding: utf-8
  file_trade:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: D:/myPython/myPython/logs/trade.log
    maxBytes: 20971520
    backupCount: 10
    encoding: utf-8
loggers:
  app:
    level: DEBUG
    handlers: [console, file_app, file_error, file_trade]
    propagate: false

root:
  level: DEBUG
  handlers: [console, file_root]
